// examples/TagInput.vue
<template>
  <div class="tag-input-container">
    <div class="tag-input-wrapper">
      <div class="tags-display">
        <span
          v-for="tag in tags"
          :key="tag"
          class="tag"
          :style="{ backgroundColor: getTagColor(tag) }"
        >
          {{ tag }}
          <button
            @click="removeTag(tag)"
            class="tag-remove"
            aria-label="Remove tag"
          >
            ×
          </button>
        </span>
      </div>
      
      <input
        v-model="inputValue"
        @keydown.enter.prevent="handleEnter"
        @keydown.backspace="handleBackspace"
        @input="handleInput"
        :placeholder="placeholder"
        class="tag-input"
        ref="inputRef"
      />
    </div>

    <!-- Suggestions dropdown -->
    <div v-if="showSuggestions && filteredSuggestions.length > 0" class="suggestions">
      <div
        v-for="(suggestion, index) in filteredSuggestions"
        :key="suggestion"
        @click="selectSuggestion(suggestion)"
        :class="['suggestion-item', { active: index === selectedIndex }]"
      >
        {{ suggestion }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue'

interface Props {
  modelValue: string[]
  existingTags?: string[]
  placeholder?: string
  maxTags?: number
}

const props = withDefaults(defineProps<Props>(), {
  existingTags: () => [],
  placeholder: 'Add tag...',
  maxTags: 10
})

const emit = defineEmits<{
  'update:modelValue': [value: string[]]
  'tag-added': [tag: string]
  'tag-removed': [tag: string]
}>()

const tags = ref<string[]>([...props.modelValue])
const inputValue = ref('')
const showSuggestions = ref(false)
const selectedIndex = ref(-1)
const inputRef = ref<HTMLInputElement | null>(null)

// Popular colors for tags
const TAG_COLORS = [
  '#3B82F6', // blue
  '#10B981', // emerald
  '#F59E0B', // amber
  '#EF4444', // red
  '#8B5CF6', // violet
  '#06B6D4', // cyan
  '#84CC16', // lime
  '#F97316', // orange
  '#EC4899', // pink
  '#6B7280', // gray
]

// Computed properties
const filteredSuggestions = computed(() => {
  if (!inputValue.value.trim()) {
    return props.existingTags.filter(tag => !tags.value.includes(tag))
  }
  
  const query = inputValue.value.toLowerCase().trim()
  return props.existingTags.filter(tag => 
    !tags.value.includes(tag) && 
    tag.toLowerCase().includes(query)
  )
})

// Methods
const getTagColor = (tag: string): string => {
  const index = tag.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0)
  return TAG_COLORS[index % TAG_COLORS.length]
}

const addTag = (tag: string) => {
  const normalizedTag = tag.trim()
  
  if (!normalizedTag) return
  if (tags.value.includes(normalizedTag)) return
  if (tags.value.length >= props.maxTags) return
  
  tags.value.push(normalizedTag)
  inputValue.value = ''
  showSuggestions.value = false
  selectedIndex.value = -1
  
  emit('update:modelValue', [...tags.value])
  emit('tag-added', normalizedTag)
}

const removeTag = (tag: string) => {
  const index = tags.value.indexOf(tag)
  if (index > -1) {
    tags.value.splice(index, 1)
    emit('update:modelValue', [...tags.value])
    emit('tag-removed', tag)
  }
}

const handleEnter = () => {
  if (selectedIndex.value >= 0 && filteredSuggestions.value[selectedIndex.value]) {
    addTag(filteredSuggestions.value[selectedIndex.value])
  } else if (inputValue.value.trim()) {
    addTag(inputValue.value)
  }
}

const handleBackspace = (e: KeyboardEvent) => {
  if (inputValue.value === '' && tags.value.length > 0) {
    removeTag(tags.value[tags.value.length - 1])
  }
}

const handleInput = () => {
  showSuggestions.value = inputValue.value.trim().length > 0 || filteredSuggestions.value.length > 0
  selectedIndex.value = -1
}

const selectSuggestion = (suggestion: string) => {
  addTag(suggestion)
}

// Watch for external changes
watch(() => props.modelValue, (newValue) => {
  tags.value = [...newValue]
}, { deep: true })

// Focus input when clicking container
const focusInput = () => {
  nextTick(() => {
    inputRef.value?.focus()
  })
}
</script>

<style scoped>
.tag-input-container {
  position: relative;
  width: 100%;
}

.tag-input-wrapper {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  padding: 8px;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  background: white;
  min-height: 42px;
  align-items: center;
  cursor: text;
}

.tag-input-wrapper:focus-within {
  outline: 2px solid #3b82f6;
  outline-offset: -1px;
  border-color: #3b82f6;
}

.tags-display {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.tag {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 10px;
  border-radius: 16px;
  font-size: 14px;
  font-weight: 500;
  color: white;
  background-color: #3b82f6;
  user-select: none;
}

.tag-remove {
  background: none;
  border: none;
  color: white;
  cursor: pointer;
  font-size: 18px;
  line-height: 1;
  padding: 0;
  margin-left: 4px;
  opacity: 0.8;
  transition: opacity 0.2s;
}

.tag-remove:hover {
  opacity: 1;
}

.tag-input {
  flex: 1;
  min-width: 120px;
  border: none;
  outline: none;
  padding: 4px 0;
  font-size: 14px;
  background: transparent;
}

.tag-input::placeholder {
  color: #9ca3af;
}

.suggestions {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  margin-top: 4px;
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  max-height: 200px;
  overflow-y: auto;
  z-index: 50;
}

.suggestion-item {
  padding: 10px 12px;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.15s;
}

.suggestion-item:hover,
.suggestion-item.active {
  background-color: #f3f4f6;
}

.suggestion-item:first-child {
  border-top-left-radius: 6px;
  border-top-right-radius: 6px;
}

.suggestion-item:last-child {
  border-bottom-left-radius: 6px;
  border-bottom-right-radius: 6px;
}
</style>

// prompt-editor/components/tag-input.tsx
"use client"

import { useState, useRef, useEffect, useMemo } from "react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Plus, Palette } from "lucide-react"

// Minimal tag type from API
type ApiTag = { id: string; name: string; color?: string }

interface TagInputProps {
  value: string
  onChange: (value: string) => void
  onAddTag: (tag: string) => void
  onCreateTag?: (name: string, color: string) => Promise<void>
  existingTags: string[]
  myTags: ApiTag[]
  placeholder?: string
}

interface SuggestionsData {
  existingTags: ApiTag[]
  canCreate: boolean
  searchQuery: string
}

// Popular colors for tags
const TAG_COLORS = [
  '#3B82F6', // blue
  '#10B981', // emerald
  '#F59E0B', // amber
  '#EF4444', // red
  '#8B5CF6', // violet
  '#06B6D4', // cyan
  '#84CC16', // lime
  '#F97316', // orange
  '#EC4899', // pink
  '#6B7280', // gray
]

export function TagInput({
  value,
  onChange,
  onAddTag,
  onCreateTag,
  existingTags,
  myTags = [],
  placeholder = "Add tag..."
}: TagInputProps) {
  const [showSuggestions, setShowSuggestions] = useState(false)
  const [selectedIndex, setSelectedIndex] = useState(-1)
  const [showColorPicker, setShowColorPicker] = useState(false)
  const [selectedColor, setSelectedColor] = useState(TAG_COLORS[0])
  const [isCreating, setIsCreating] = useState(false)
  const [isOpen, setIsOpen] = useState(false)

  const inputRef = useRef<HTMLInputElement>(null)
  const suggestionsRef = useRef<HTMLDivElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  // Debug log for verification
  useEffect(() => {
    console.log('TagInput received myTags:', myTags?.length, myTags)
  }, [myTags])

  // Suggestions: filter by tags + add option to create new
  const suggestions = useMemo((): SuggestionsData => {
    const q = value.trim().toLowerCase()
    if (!q) {
      return {
        existingTags: [],
        canCreate: false,
        searchQuery: ''
      }
    }

    const matchingTags = myTags.filter(t =>
      t.name.toLowerCase().includes(q) && !existingTags.includes(t.name)
    ).slice(0, 15)

    // Check if there's an exact match
    const exactMatch = myTags.find(t => t.name.toLowerCase() === q)
    const canCreate = q.length >= 2 && !exactMatch && !existingTags.includes(q)

    return {
      existingTags: matchingTags,
      canCreate,
      searchQuery: q
    }
  }, [value, myTags, existingTags])

  const totalSuggestions = suggestions.existingTags.length + (suggestions.canCreate ? 1 : 0)

  useEffect(() => {
    if (value.trim() && totalSuggestions > 0) {
      setIsOpen(true)
      setShowSuggestions(true)
      setSelectedIndex(-1)
    } else {
      setIsOpen(false)
      setShowSuggestions(false)
      setShowColorPicker(false)
      setSelectedIndex(-1)
    }
  }, [value, totalSuggestions])

  // Close on click outside component
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false)
        setShowSuggestions(false)
        setShowColorPicker(false)
      }
    }

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside)
      return () => {
        document.removeEventListener('mousedown', handleClickOutside)
      }
    }
  }, [isOpen])

  const handleCreateTag = async () => {
    if (!onCreateTag || !suggestions.canCreate) return

    setIsCreating(true)
    try {
      await onCreateTag(suggestions.searchQuery, selectedColor)
      onChange("")
      setIsOpen(false)
      setShowSuggestions(false)
      setShowColorPicker(false)
    } catch (error) {
      console.error('Failed to create tag:', error)
    } finally {
      setIsCreating(false)
    }
  }

  const showCreateForm = () => {
    setShowColorPicker(true)
    setSelectedIndex(suggestions.existingTags.length)
  }

  const hideCreateForm = () => {
    setShowColorPicker(false)
    setSelectedIndex(-1)
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!showSuggestions) {
      if (e.key === "Enter") {
        e.preventDefault()
        // If there's exact match - add it
        const exact = myTags.find(t => t.name.toLowerCase() === value.trim().toLowerCase())
        if (exact && !existingTags.includes(exact.name)) {
          onAddTag(exact.name)
          onChange("")
          setIsOpen(false)
          setShowSuggestions(false)
        } else if (suggestions.canCreate && onCreateTag) {
          // Create new tag with default color
          showCreateForm()
        }
      }
      return
    }

    switch (e.key) {
      case "ArrowDown":
        e.preventDefault()
        setSelectedIndex((prev) => Math.min(prev + 1, totalSuggestions - 1))
        break
      case "ArrowUp":
        e.preventDefault()
        setSelectedIndex((prev) => Math.max(prev - 1, -1))
        break
      case "Enter":
        e.preventDefault()
        if (selectedIndex >= 0) {
          if (selectedIndex < suggestions.existingTags.length) {
            // Selected existing tag
            const selectedTag = suggestions.existingTags[selectedIndex]
            onAddTag(selectedTag.name)
            onChange("")
            setIsOpen(false)
            setShowSuggestions(false)
          } else {
            // Selected option to create new tag
            if (showColorPicker) {
              handleCreateTag()
            } else {
              showCreateForm()
            }
          }
        } else {
          // Check exact match or create new
          const exact = myTags.find(t => t.name.toLowerCase() === value.trim().toLowerCase())
          if (exact && !existingTags.includes(exact.name)) {
            onAddTag(exact.name)
            onChange("")
            setIsOpen(false)
            setShowSuggestions(false)
          } else if (suggestions.canCreate && onCreateTag) {
            showCreateForm()
          }
        }
        break
      case "Escape":
        setIsOpen(false)
        setShowSuggestions(false)
        setShowColorPicker(false)
        setSelectedIndex(-1)
        break
    }
  }

  const handleSuggestionClick = (tag: ApiTag) => {
    if (!existingTags.includes(tag.name)) onAddTag(tag.name)
    onChange("")
    setIsOpen(false)
    setShowSuggestions(false)
    inputRef.current?.focus()
  }

  return (
    <div ref={containerRef} className="relative">
      <Input
        ref={inputRef}
        placeholder={placeholder}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onKeyDown={handleKeyDown}
        onFocus={() => {
          if (totalSuggestions > 0) {
            setIsOpen(true)
            setShowSuggestions(true)
          }
        }}
        className="h-8 text-sm"
      />

      {isOpen && showSuggestions && totalSuggestions > 0 && (
        <div
          ref={suggestionsRef}
          className="absolute z-50 w-full mt-1 bg-white border border-gray-200 rounded-md shadow-lg max-h-64 overflow-y-auto"
        >
          {/* Existing tags */}
          {suggestions.existingTags.map((suggestion: ApiTag, index: number) => (
            <div
              key={suggestion.id}
              className={`px-3 py-2 cursor-pointer hover:bg-gray-50 ${index === selectedIndex ? "bg-blue-50" : ""}`}
              onClick={() => handleSuggestionClick(suggestion)}
            >
              <div className="flex items-center justify-between">
                <span className="font-medium text-sm">{suggestion.name}</span>
                {suggestion.color && (
                  <div
                    className="w-4 h-4 rounded-full border border-gray-200"
                    style={{ backgroundColor: suggestion.color }}
                  />
                )}
              </div>
            </div>
          ))}

          {/* Option to create new tag */}
          {suggestions.canCreate && onCreateTag && (
            <div
              className={`border-t border-gray-100 ${selectedIndex === suggestions.existingTags.length ? "bg-blue-50" : ""}`}
            >
              {!showColorPicker ? (
                <div
                  className="px-3 py-2 cursor-pointer hover:bg-gray-50 flex items-center gap-2 text-blue-600"
                  onClick={showCreateForm}
                >
                  <Plus className="w-4 h-4" />
                  <span className="text-sm font-medium">Create "{suggestions.searchQuery}"</span>
                </div>
              ) : (
                <div className="p-3 border-t border-gray-100">
                  <div className="flex items-center gap-2 mb-2">
                    <Palette className="w-4 h-4 text-gray-600" />
                    <span className="text-sm font-medium">Choose color for "{suggestions.searchQuery}"</span>
                  </div>

                  <div className="flex flex-wrap gap-2 mb-3">
                    {TAG_COLORS.map((color: string) => (
                      <button
                        key={color}
                        type="button"
                        onClick={() => setSelectedColor(color)}
                        className={`w-6 h-6 rounded-full border-2 transition-all ${
                          selectedColor === color 
                            ? 'border-gray-800 ring-2 ring-blue-200' 
                            : 'border-gray-200 hover:border-gray-400'
                        }`}
                        style={{ backgroundColor: color }}
                      />
                    ))}
                  </div>

                  <div className="flex gap-2">
                    <Button
                      type="button"
                      size="sm"
                      onClick={handleCreateTag}
                      disabled={isCreating}
                      className="flex-1 h-7 text-xs"
                    >
                      {isCreating ? "Creating..." : "Create Tag"}
                    </Button>
                    <Button
                      type="button"
                      size="sm"
                      variant="outline"
                      onClick={hideCreateForm}
                      className="h-7 text-xs"
                    >
                      Cancel
                    </Button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      <div className="mt-1 text-[11px] text-gray-500">
        {myTags && myTags.length > 0
          ? `${myTags.length} tags available • Type to search or create new`
          : myTags && Array.isArray(myTags) && myTags.length === 0
            ? "No tags found • Type to create your first tag"
            : "Loading tags..."}
      </div>
    </div>
  )
}
